name: Upload Artefact
on:
  workflow_dispatch:

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: mkdir -p artifacts
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifacts/artifact.txt