name: exo_angular
on:
  push:
    branches: [main, develop, features/*, hotfix/*]
  pull_request:
    branches: [main, develop]

jobs:

  conventional_commits:

    name: conventional_commits
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du nom de la branche
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Vérification évènement/branche
        if: github.event_name == 'push' && (startsWith(steps.extract_branch.outputs.branch, 'main') || startsWith(steps.extract_branch.outputs.branch, 'develop'))
        run: echo "Les push ne sont pas autorisés sur cette branche" && exit 1

      - name: Vérification commit conventionnel sur les branches hotfix et features
        if: (startsWith(steps.extract_branch.outputs.branch, 'hotfix') || startsWith(steps.extract_branch.outputs.branch, 'features')) && ! (startsWith(github.event.head_commit.message, 'fix:' ) || ! startsWith(github.event.head_commit.message, 'feat:'))
        run: echo "Le message du commit n'est pas conventionnel" && echo ${{steps.extract_branch.outputs.branch}} && exit 1

