name: exo_angular
on:
  push:
    branches: [features/*, hotfix/*]
  pull_request:
    branches: [main, develop, features/*]

jobs:

  conventional_commits:
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/hotfix') || startsWith(github.ref, 'refs/heads/features'))
    name: conventional_commits
    runs-on: ubuntu-latest

    steps:
      - name: Affichage du message commit & nom de branche
        run: echo ${{github.ref}} && echo ${{github.event.head_commit.message}}

      - name: Vérification commit conventionnel sur les branches hotfix et features
        if: (!startsWith(github.event.head_commit.message, 'fix:' ) && !startsWith(github.event.head_commit.message, 'feat:'))
        run: echo "Le message du commit n'est pas conventionnel" && exit 1

  tests_on_node_versions:
    name: tests_on_node_versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14, 16]

    steps:
      - run: echo ${{ github.event.pull_request.ref }} && echo ${{ github.event.pull_request.base_ref }}
      if: github.event_name == 'pull_request' && startsWith(github.event.pull_request.ref, 'refs/heads/features') && startsWith(github.event.pull_request.base_ref, 'refs/heads/develop')
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Test de node v${{ matrix.version }} et création de l'artefact
        run: npm run test:coverage > artifact.txt

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt

      - name: Téléchargement artefact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: read-file
        run: cat artifact.txt