name: Upload Artefact
on:
  workflow_dispatch:

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: mkdir -p path/to/artifact
        run: echo "coucou" > artifact.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact.txt