name: tp_node
on:
  push:
    branches: [features/*, hotfix/*]

jobs:

  # Vérifie que le message de commit soit conventionnel ou non
  conventional_commits:
    if: github.event_name == 'push' && (startsWith(github.ref_name, 'hotfix') || startsWith(github.ref_name, 'features'))
    name: conventional_commits
    runs-on: ubuntu-latest

    steps:
      - name: Affichage du nom de branche & du message commit
        run: echo ${{github.ref_name}} && echo ${{github.event.head_commit.message}}

      - name: Vérification commit conventionnel sur les branches hotfix et features
        if: (!startsWith(github.event.head_commit.message, 'fix:' ) && !startsWith(github.event.head_commit.message, 'feat:'))
        run: echo "Le message du commit n'est pas conventionnel" && exit 1